title_tr: "WoaBeauty - Kamer Yüzer Güzellik Evi"
title_en: "WoaBeauty - Kamer Yüzer House of Beauty"
email: "kameryuzer@gmail.com"
phone_number: "+90 545 122 96 56"
whatsapp: "+90 545 122 96 56"
description_tr: >
  WoaBeauty 
  - Kamer Yüzer Güzellik Evi
description_en: >-
  WoaBeauty 
  - Kamer Yüzer House of Beauty
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kameryuzer.com" # the base hostname & protocol for your site, e.g. http://example.com
facebook_url: https://www.facebook.com/
twitter_url: https://twitter.com/
tiktok_url: https://www.tiktok.com/
instagram_url: https://www.instagram.com/WoaBeautyLevent
logo: "assets/img/logo/logo.png"
mailchimp_list: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=342411fb35"
mailchimp_input_name: "b_307862c135e4548eecf86f389_342411fb35"

permalink: "/:title"


# Build settings
markdown: kramdown
theme: minima 
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-sitemap

cover_image: "assets/img/bg/page-title.jpg"


#collections
collections:
  features:
    output: true
  services:
    output: true

# jekyll-multiple-languages-plugin settings:
languages: ["tr"]
exclude_from_localizations: ["images"]

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'

feed:
  collections:
    posts:
      path: "/index.xml"
